#!/bin/bash

set -e 


echo "Jinfo Path: /usr/lib/jvm/.${JDK_NAME}.jinfo"

FILE="/usr/lib/jvm/.${JDK_NAME}.jinfo"

echo "name=${JDK_NAME}" >> "${FILE}"
echo "alias=adoptOpenJdk-jdk11" >> "${FILE}"
echo "priority=180" >> "${FILE}"
echo "section=main" >> "${FILE}"
echo "" >> "${FILE}"
echo "hl rmid /usr/lib/jvm/${JDK_NAME}/jre/bin/rmid" >> "${FILE}"
echo "hl java /usr/lib/jvm/${JDK_NAME}/jre/bin/java" >> "${FILE}"
echo "hl keytool /usr/lib/jvm/${JDK_NAME}/jre/bin/keytool" >> "${FILE}"
echo "hl pack200 /usr/lib/jvm/${JDK_NAME}/jre/bin/pack200" >> "${FILE}"
echo "hl rmiregistry /usr/lib/jvm/${JDK_NAME}/jre/bin/rmiregistry" >> "${FILE}"
echo "hl unpack200 /usr/lib/jvm/${JDK_NAME}/jre/bin/unpack200" >> "${FILE}"
echo "hl orbd /usr/lib/jvm/${JDK_NAME}/jre/bin/orbd" >> "${FILE}"
echo "hl servertool /usr/lib/jvm/${JDK_NAME}/jre/bin/servertool" >> "${FILE}"
echo "hl tnameserv /usr/lib/jvm/${JDK_NAME}/jre/bin/tnameserv" >> "${FILE}"
echo "hl jexec /usr/lib/jvm/${JDK_NAME}/jre/lib/jexec" >> "${FILE}"
echo "jre policytool /usr/lib/jvm/${JDK_NAME}/jre/bin/policytool" >> "${FILE}"
echo "jdk jconsole /usr/lib/jvm/${JDK_NAME}/bin/jconsole" >> "${FILE}"
echo "jdk wsimport /usr/lib/jvm/${JDK_NAME}/bin/wsimport" >> "${FILE}"
echo "jdk rmic /usr/lib/jvm/${JDK_NAME}/bin/rmic" >> "${FILE}"
echo "jdk jinfo /usr/lib/jvm/${JDK_NAME}/bin/jinfo" >> "${FILE}"
echo "jdk jsadebugd /usr/lib/jvm/${JDK_NAME}/bin/jsadebugd" >> "${FILE}"
echo "jdk native2ascii /usr/lib/jvm/${JDK_NAME}/bin/native2ascii" >> "${FILE}"
echo "jdk jstat /usr/lib/jvm/${JDK_NAME}/bin/jstat" >> "${FILE}"
echo "jdk javac /usr/lib/jvm/${JDK_NAME}/bin/javac" >> "${FILE}"
echo "jdk javah /usr/lib/jvm/${JDK_NAME}/bin/javah" >> "${FILE}"
echo "jdk idlj /usr/lib/jvm/${JDK_NAME}/bin/idlj" >> "${FILE}"
echo "jdk jstack /usr/lib/jvm/${JDK_NAME}/bin/jstack" >> "${FILE}"
echo "jdk jrunscript /usr/lib/jvm/${JDK_NAME}/bin/jrunscript" >> "${FILE}"
echo "jdk javadoc /usr/lib/jvm/${JDK_NAME}/bin/javadoc" >> "${FILE}"
echo "jdk javap /usr/lib/jvm/${JDK_NAME}/bin/javap" >> "${FILE}"
echo "jdk jar /usr/lib/jvm/${JDK_NAME}/bin/jar" >> "${FILE}"
echo "jdk extcheck /usr/lib/jvm/${JDK_NAME}/bin/extcheck" >> "${FILE}"
echo "jdk schemagen /usr/lib/jvm/${JDK_NAME}/bin/schemagen" >> "${FILE}"
echo "jdk jps /usr/lib/jvm/${JDK_NAME}/bin/jps" >> "${FILE}"
echo "jdk xjc /usr/lib/jvm/${JDK_NAME}/bin/xjc" >> "${FILE}"
echo "jdk jarsigner /usr/lib/jvm/${JDK_NAME}/bin/jarsigner" >> "${FILE}"
echo "jdk jmap /usr/lib/jvm/${JDK_NAME}/bin/jmap" >> "${FILE}"
echo "jdk appletviewer /usr/lib/jvm/${JDK_NAME}/bin/appletviewer" >> "${FILE}"
echo "jdk jstatd /usr/lib/jvm/${JDK_NAME}/bin/jstatd" >> "${FILE}"
echo "jdk jhat /usr/lib/jvm/${JDK_NAME}/bin/jhat" >> "${FILE}"
echo "jdk jdb /usr/lib/jvm/${JDK_NAME}/bin/jdb" >> "${FILE}"
echo "jdk serialver /usr/lib/jvm/${JDK_NAME}/bin/serialver" >> "${FILE}"
echo "jdk wsgen /usr/lib/jvm/${JDK_NAME}/bin/wsgen" >> "${FILE}"
echo "jdk jcmd /usr/lib/jvm/${JDK_NAME}/bin/jcmd" >> "${FILE}"
echo "jdk javafxpackager /usr/lib/jvm/${JDK_NAME}/bin/javafxpackager" >> "${FILE}"
echo "jdk javapackager /usr/lib/jvm/${JDK_NAME}/bin/javapackager" >> "${FILE}"
echo "jdk javaws /usr/lib/jvm/${JDK_NAME}/bin/javaws" >> "${FILE}"
echo "jdk jcontrol /usr/lib/jvm/${JDK_NAME}/bin/jcontrol" >> "${FILE}"
echo "jdk jdeps /usr/lib/jvm/${JDK_NAME}/bin/jdeps" >> "${FILE}"
echo "jdk jjs /usr/lib/jvm/${JDK_NAME}/bin/jjs" >> "${FILE}"
echo "jdk jmc /usr/lib/jvm/${JDK_NAME}/bin/jmc" >> "${FILE}"
echo "jdk jvisualvm /usr/lib/jvm/${JDK_NAME}/bin/jvisualvm" >> "${FILE}"


cat $FILE