#!/bin/bash
update-alternatives --install /usr/bin/appletviewer appletviewer "/usr/lib/jvm/${FN}/bin/appletviewer" 180
update-alternatives --install /usr/bin/extcheck extcheck "/usr/lib/jvm/${FN}/bin/extcheck" 180
update-alternatives --install /usr/bin/idlj idlj "/usr/lib/jvm/${FN}/bin/idlj" 180
update-alternatives --install /usr/bin/jar jar "/usr/lib/jvm/${FN}/bin/jar" 180
update-alternatives --install /usr/bin/jarsigner jarsigner "/usr/lib/jvm/${FN}/bin/jarsigner" 180
update-alternatives --install /usr/bin/java java "/usr/lib/jvm/${FN}/jre/bin"/java 180
update-alternatives --install /usr/bin/javac javac "/usr/lib/jvm/${FN}/bin/javac" 180
update-alternatives --install /usr/bin/javadoc javadoc "/usr/lib/jvm/${FN}/bin/javadoc" 180
update-alternatives --install /usr/bin/javafxpackager javafxpackager "/usr/lib/jvm/${FN}/bin/javafxpackager" 180
update-alternatives --install /usr/bin/javah javah "/usr/lib/jvm/${FN}/bin/javah" 180
update-alternatives --install /usr/bin/javap javap "/usr/lib/jvm/${FN}/bin/javap" 180
update-alternatives --install /usr/bin/javapackager javapackager "/usr/lib/jvm/${FN}/bin/javapackager" 180
update-alternatives --install /usr/bin/javaws javaws "/usr/lib/jvm/${FN}/bin/javaws" 180
update-alternatives --install /usr/bin/jcmd jcmd "/usr/lib/jvm/${FN}/bin/jcmd" 180
update-alternatives --install /usr/bin/jconsole jconsole "/usr/lib/jvm/${FN}/bin/jconsole" 180
update-alternatives --install /usr/bin/jcontrol jcontrol "/usr/lib/jvm/${FN}/bin/jcontrol" 180
update-alternatives --install /usr/bin/jdb jdb "/usr/lib/jvm/${FN}/bin/jdb" 180
update-alternatives --install /usr/bin/jdeps jdeps "/usr/lib/jvm/${FN}/bin/jdeps" 180
update-alternatives --install /usr/bin/jexec jexec "/usr/lib/jvm/${FN}/jre/lib"/jexec 180
update-alternatives --install /usr/bin/jhat jhat "/usr/lib/jvm/${FN}/bin/jhat" 180
update-alternatives --install /usr/bin/jinfo jinfo "/usr/lib/jvm/${FN}/bin/jinfo" 180
update-alternatives --install /usr/bin/jjs jjs "/usr/lib/jvm/${FN}/bin/jjs" 180
update-alternatives --install /usr/bin/jmap jmap "/usr/lib/jvm/${FN}/bin/jmap" 180
update-alternatives --install /usr/bin/jmc jmc "/usr/lib/jvm/${FN}/bin/jmc" 180
update-alternatives --install /usr/bin/jps jps "/usr/lib/jvm/${FN}/bin/jps" 180
update-alternatives --install /usr/bin/jrunscript jrunscript "/usr/lib/jvm/${FN}/bin/jrunscript" 180
update-alternatives --install /usr/bin/jsadebugd jsadebugd "/usr/lib/jvm/${FN}/bin/jsadebugd" 180
update-alternatives --install /usr/bin/jstack jstack "/usr/lib/jvm/${FN}/bin/jstack" 180
update-alternatives --install /usr/bin/jstat jstat "/usr/lib/jvm/${FN}/bin/jstat" 180
update-alternatives --install /usr/bin/jstatd jstatd "/usr/lib/jvm/${FN}/bin/jstatd" 180
update-alternatives --install /usr/bin/jvisualvm jvisualvm "/usr/lib/jvm/${FN}/bin/jvisualvm" 180
update-alternatives --install /usr/bin/keytool keytool "/usr/lib/jvm/${FN}/jre/bin"/keytool 180
update-alternatives --install /usr/bin/native2ascii native2ascii "/usr/lib/jvm/${FN}/bin/native2ascii" 180
update-alternatives --install /usr/bin/orbd orbd "/usr/lib/jvm/${FN}/jre/bin"/orbd 180
update-alternatives --install /usr/bin/pack200 pack200 "/usr/lib/jvm/${FN}/jre/bin"/pack200 180
update-alternatives --install /usr/bin/policytool policytool "/usr/lib/jvm/${FN}/jre/bin"/policytool 180
update-alternatives --install /usr/bin/rmic rmic "/usr/lib/jvm/${FN}/bin/rmic" 180
update-alternatives --install /usr/bin/rmid rmid "/usr/lib/jvm/${FN}/jre/bin"/rmid 180
update-alternatives --install /usr/bin/rmiregistry rmiregistry "/usr/lib/jvm/${FN}/jre/bin"/rmiregistry 180
update-alternatives --install /usr/bin/schemagen schemagen "/usr/lib/jvm/${FN}/bin/schemagen" 180
update-alternatives --install /usr/bin/serialver serialver "/usr/lib/jvm/${FN}/bin/serialver" 180
update-alternatives --install /usr/bin/servertool servertool "/usr/lib/jvm/${FN}/jre/bin"/servertool 180
update-alternatives --install /usr/bin/tnameserv tnameserv "/usr/lib/jvm/${FN}/jre/bin"/tnameserv 180
update-alternatives --install /usr/bin/unpack200 unpack200 "/usr/lib/jvm/${FN}/jre/bin"/unpack200 180
update-alternatives --install /usr/bin/wsgen wsgen "/usr/lib/jvm/${FN}/bin/wsgen" 180
update-alternatives --install /usr/bin/wsimport wsimport "/usr/lib/jvm/${FN}/bin/wsimport" 180
update-alternatives --install /usr/bin/xjc xjc "/usr/lib/jvm/${FN}/bin/xjc" 180
