#!/bin/bash

set -e 


echo "Jinfo Path: /usr/lib/jvm/.${JDK_NAME}.jinfo"

FILE="/usr/lib/jvm/.${JDK_NAME}.jinfo"

echo "name=${JDK_NAME}" >> "${FILE}"
echo "alias=adoptOpenJdk-jdk8" >> "${FILE}"
echo "priority=180" >> "${FILE}"
echo "section=main" >> "${FILE}"
echo "" >> "${FILE}"
echo "jdk appletviewer /usr/lib/jvm/${JDK_NAME}/bin/appletviewer" >> "${FILE}"
echo "jdk clhsdb /usr/lib/jvm/${JDK_NAME}/bin/clhsdb" >> "${FILE}"
echo "jdk extcheck /usr/lib/jvm/${JDK_NAME}/bin/extcheck" >> "${FILE}"
echo "jdk hsdb /usr/lib/jvm/${JDK_NAME}/bin/hsdb" >> "${FILE}"
echo "jdk idlj /usr/lib/jvm/${JDK_NAME}/bin/idlj" >> "${FILE}"
echo "jdk jar /usr/lib/jvm/${JDK_NAME}/bin/jar" >> "${FILE}"
echo "jdk jarsigner /usr/lib/jvm/${JDK_NAME}/bin/jarsigner" >> "${FILE}"
echo "jdk java /usr/lib/jvm/${JDK_NAME}/bin/java" >> "${FILE}"
echo "jdk java-rmi.cgi /usr/lib/jvm/${JDK_NAME}/bin/java-rmi.cgi" >> "${FILE}"
echo "jdk javac /usr/lib/jvm/${JDK_NAME}/bin/javac" >> "${FILE}"
echo "jdk javadoc /usr/lib/jvm/${JDK_NAME}/bin/javadoc" >> "${FILE}"
echo "jdk javah /usr/lib/jvm/${JDK_NAME}/bin/javah" >> "${FILE}"
echo "jdk javap /usr/lib/jvm/${JDK_NAME}/bin/javap" >> "${FILE}"
echo "jdk jcmd /usr/lib/jvm/${JDK_NAME}/bin/jcmd" >> "${FILE}"
echo "jdk jconsole /usr/lib/jvm/${JDK_NAME}/bin/jconsole" >> "${FILE}"
echo "jdk jdb /usr/lib/jvm/${JDK_NAME}/bin/jdb" >> "${FILE}"
echo "jdk jdeps /usr/lib/jvm/${JDK_NAME}/bin/jdeps" >> "${FILE}"
echo "jdk jhat /usr/lib/jvm/${JDK_NAME}/bin/jhat" >> "${FILE}"
echo "jdk jinfo /usr/lib/jvm/${JDK_NAME}/bin/jinfo" >> "${FILE}"
echo "jdk jjs /usr/lib/jvm/${JDK_NAME}/bin/jjs" >> "${FILE}"
echo "jdk jmap /usr/lib/jvm/${JDK_NAME}/bin/jmap" >> "${FILE}"
echo "jdk jps /usr/lib/jvm/${JDK_NAME}/bin/jps" >> "${FILE}"
echo "jdk jrunscript /usr/lib/jvm/${JDK_NAME}/bin/jrunscript" >> "${FILE}"
echo "jdk jsadebugd /usr/lib/jvm/${JDK_NAME}/bin/jsadebugd" >> "${FILE}"
echo "jdk jstack /usr/lib/jvm/${JDK_NAME}/bin/jstack" >> "${FILE}"
echo "jdk jstat /usr/lib/jvm/${JDK_NAME}/bin/jstat" >> "${FILE}"
echo "jdk jstatd /usr/lib/jvm/${JDK_NAME}/bin/jstatd" >> "${FILE}"
echo "jdk keytool /usr/lib/jvm/${JDK_NAME}/bin/keytool" >> "${FILE}"
echo "jdk native2ascii /usr/lib/jvm/${JDK_NAME}/bin/native2ascii" >> "${FILE}"
echo "jdk orbd /usr/lib/jvm/${JDK_NAME}/bin/orbd" >> "${FILE}"
echo "jdk pack200 /usr/lib/jvm/${JDK_NAME}/bin/pack200" >> "${FILE}"
echo "jdk policytool /usr/lib/jvm/${JDK_NAME}/bin/policytool" >> "${FILE}"
echo "jdk rmic /usr/lib/jvm/${JDK_NAME}/bin/rmic" >> "${FILE}"
echo "jdk rmid /usr/lib/jvm/${JDK_NAME}/bin/rmid" >> "${FILE}"
echo "jdk rmiregistry /usr/lib/jvm/${JDK_NAME}/bin/rmiregistry" >> "${FILE}"
echo "jdk schemagen /usr/lib/jvm/${JDK_NAME}/bin/schemagen" >> "${FILE}"
echo "jdk serialver /usr/lib/jvm/${JDK_NAME}/bin/serialver" >> "${FILE}"
echo "jdk servertool /usr/lib/jvm/${JDK_NAME}/bin/servertool" >> "${FILE}"
echo "jdk tnameserv /usr/lib/jvm/${JDK_NAME}/bin/tnameserv" >> "${FILE}"
echo "jdk unpack200 /usr/lib/jvm/${JDK_NAME}/bin/unpack200" >> "${FILE}"
echo "jdk wsgen /usr/lib/jvm/${JDK_NAME}/bin/wsgen" >> "${FILE}"
echo "jdk wsimport /usr/lib/jvm/${JDK_NAME}/bin/wsimport" >> "${FILE}"
echo "jdk xjc /usr/lib/jvm/${JDK_NAME}/bin/xjc" >> "${FILE}"

cat $FILE
