name: jdk-image-builder
on:
  push:
  release:
    types: [published]
jobs:
  publisher:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PLATFORM_BOT_GITHUB_USER }}
          password: ${{ secrets.PLATFORM_BOT_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: run ci.sh
        run: |
          ./ci.sh
