name: jdk-image-builder
on:
  push:
  release:
    types: [published]
jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.PLATFORM_BOT_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.PLATFORM_BOT_GITHUB_TOKEN }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: $GITHUB_TOKEN
      - name: run ci.sh
        run: |
          ./ci.sh
